Bap composite
ESA-APEx/apex_algorithms pull request #41
Opened 2024-10-11 12:37 UTC by VincentVerelst

I made a minimally parametrized UDP for a BAP composite algorithm. Current parameters are temporal_extent, spatial_extent and bands (optional). 

Currently, max_cloud_cover, spatial_resolution, score weights and compositing window are fixed. 

During the process of adding this algortihm, I've gathered some comments which I'm happy to discuss!

2024-10-11 19:02 UTC, jdries requested changes
a few smaller suggestions. If we have time, would be good to check out the artifacts.

2024-10-11 19:02 UTC, jdries commented on algorithm_catalog/bap_composite_files/bap_composite_description.md
> +The relative cost is 0.2 CDSE platform credits per km² for a 1 month input window.
for 3 bands.

2024-10-14 12:27 UTC, VincentVerelst commented on algorithm_catalog/bap_composite.json
> +      "href": "https://s3.waw3-1.cloudferro.com/swift/v1/APEx-examples/bap_composite_denmark/collection.json"
I checked the raw S2 data and it seems that in this month there just aren't any dates for which these pixels weren't clouded: https://openeo.dataspace.copernicus.eu/openeo/1.1/jobs/j-24101448a47641ec9e23fa41b37ad67c/results/NTc3ZjY1NDEtYzU2NS00Nzk4LWEyY2QtNWZjNDJkOTY0MDFi/f89125a1e86264618a79312746b96a24?expires=1729513023

2024-10-14 14:41 UTC, VincentVerelst commented on algorithm_catalog/bap_composite.json
> +      "href": "https://s3.waw3-1.cloudferro.com/swift/v1/APEx-examples/bap_composite_denmark/collection.json"
The STAC collection should now reference a better month with little to no artifacts

2024-10-24 08:08 UTC, jdries approved these changes
approved, I would merge it, allowing integration and further evaluation.

2024-10-24 08:42 UTC, merged